typography_spectrum: 0.8847336051985621
content_rating:
  adult: false
color:
  brandColors:
    - '#B8D0D8'
    - '#000830'
    - '#486888'
    - '#2090F8'
    - '#000000'
  brandStrength: 0.25
  lightness: 0.375
  saturation: 0.5
  rhythmicContrast: 0.587211
opengraph:
  type: ''
  appId: ''
layout_spectrum: 0.25255477242171764
analytics:
  google: UA-74806505-2
author:
  name: ''
  url: ''
  email: ''
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/4bf65d58-61ab-40d2-a2c2-2a008aee7149.jpg
name: RiSK
cta: {}
navigation:
  - name: Our Goal
    id: 99ddde07-53ff-438d-acd1-37601090d4f5
    type: content
  - name: 'Our Process '
    id: 6efcb629-88b1-424f-9011-a5a433184de8
    type: content
  - name: Our Services
    id: e18c7169-f550-4a77-b34e-06ed19b6a644
    type: content
  - name: Pricing
    id: fb783315-6da5-4f8c-9137-fa6683ff9747
    type: content
  - name: About Us
    id: 5e0c6786-c02e-4729-8a19-283f857ae569
    type: content
title: 'Landscape. Architectural Design & Interior Designing '
description: 'Landscape, Architectural Design & Interior Designing'
purpose: []
