name: RiSK
layout_spectrum: 0
typography_spectrum: 0.87568
cta: {}
analytics:
  google: UA-74806505-2
opengraph:
  type: ''
  appId: ''
color:
  brandColors:
    - '#B8D0D8'
    - '#000830'
    - '#486888'
    - '#2090F8'
    - '#000000'
  brandStrength: 0.25
  lightness: 0.375
  saturation: 0.5
  rhythmicContrast: 0.587211
purpose: []
title: 'Landscape. Architectural. Interior Design. '
author:
  name: ''
  url: ''
  email: ''
content_rating:
  adult: false
navigation:
  - name: Our Goal
    id: 99ddde07-53ff-438d-acd1-37601090d4f5
    type: content
  - name: 'Our Process '
    id: 6efcb629-88b1-424f-9011-a5a433184de8
    type: content
  - name: Our Services
    id: e18c7169-f550-4a77-b34e-06ed19b6a644
    type: content
  - name: Pricing
    id: fb783315-6da5-4f8c-9137-fa6683ff9747
    type: content
  - name: About Us
    id: 5e0c6786-c02e-4729-8a19-283f857ae569
    type: content
