name: RiSK
favicon: null
layout_spectrum: 0
typography_spectrum: 0.15563832502812147
title: 'Customizing Homes for You!'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#4f4f4f'
    - '#bfbfbf'
    - '#858585'
  brandStrength: 0.005691910395398736
  lightness: 0.6610749335959554
  saturation: 0.1257169065065682
  rhythmicContrast: 0.5872112438082695
purpose: []
