typography_spectrum: 0.87568
color:
  brandColors:
    - '#B8D0D8'
    - '#000830'
    - '#486888'
    - '#2090F8'
    - '#000000'
  brandStrength: 0.25
  lightness: 0.375
  saturation: 0.5
  rhythmicContrast: 0.587211
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0
analytics:
  google: UA-74806505-2
  facebook: null
  twitter: null
name: RiSK
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: ''
purpose: []
