name: RiSK
favicon: null
layout_spectrum: 0
typography_spectrum: 0.87568
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-74806505-2
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8D0D8'
    - '#000830'
    - '#486888'
    - '#2090F8'
    - '#000000'
  brandStrength: 0.25
  lightness: 0.375
  saturation: 0.5
  rhythmicContrast: 0.587211
purpose: []
